# -*- coding: utf-8 -*-
"""aya_expanse_sft_bengali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryPYXzqb7oIn2fchMLdCNSIH5KfyEtv4

# Fine-Tuning Aya Expanse On More Languages

While Aya Expanse models are highly optimized through post-training for instruction following performance on 23 languages which cover half of the world's population, these models were pre-trained on a very large corpus of text which contains many more langauges. Knowledge of many languages acquired in pre-training combined with strong, cross-lingual representations means that Aya Expanse models often perform well in languages that were not explicitly optimized for in post-training, even with little to no additional training data in that language.

We can further improve the performance of Aya Expanse models on a language which is not part of the original set of 23 optimized languages by supervised fine-tuning (SFT) on a small dataset of instructions for a particular target language. In this notebook, we provide an example of fine-tuning Aya Expanse on a Bengali dataset and demonstrate that with a small amount of fine-tuning data, we can train Aya Expanse to perform well in Bengali.
"""

# install dependencies
# !pip install -U bitsandbytes transformers peft accelerate trl datasets sentencepiece wandb

# optional for faster, lower memory usage attention
# !pip install flash-attn --no-build-isolation

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,TrainingArguments
from peft import LoraConfig
import torch
from datasets import load_dataset
from trl import SFTTrainer

USE_GPU = True
if USE_GPU:
    device = "cuda:0"
else:
    device = "cpu"

# you may want to change the following parameters depending on your GPU configuration

# free T4 instance
# QUANTIZE_4BIT = True
# USE_GRAD_CHECKPOINTING = True
# TRAIN_BATCH_SIZE = 2
# TRAIN_MAX_SEQ_LENGTH = 512
# USE_FLASH_ATTENTION = False
# GRAD_ACC_STEPS = 16

# equivalent A100 setting
QUANTIZE_4BIT = True
USE_GRAD_CHECKPOINTING = True
TRAIN_BATCH_SIZE = 16
TRAIN_MAX_SEQ_LENGTH = 512
USE_FLASH_ATTENTION = True
GRAD_ACC_STEPS = 2

"""# Loading and Testing the Base Model
Let's load the Aya Expanse 8B model and tokenizer. If you would like to use Aya Expanse 32B, change `MODEL_NAME` to `"CohereForAI/aya-expanse-32b"`.

"""

MODEL_PATH = "./models/aya-expanse-8b"

# Load Model
quantization_config = None
if QUANTIZE_4BIT:
  quantization_config = BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_use_double_quant=True,
      bnb_4bit_compute_dtype=torch.bfloat16,
  )

attn_implementation = None
if USE_FLASH_ATTENTION:
  attn_implementation="flash_attention_2"

model = AutoModelForCausalLM.from_pretrained(
          MODEL_PATH,
          quantization_config=quantization_config,
          attn_implementation=attn_implementation,
          torch_dtype=torch.bfloat16,
        )
model = model.to(device)

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)

def get_message_format(prompts):
  messages = []

  for p in prompts:
    messages.append(
        [{"role": "user", "content": p}]
      )

  return messages

def generate_aya(
      model,
      prompts,
      temperature=0.75,
      top_p=1.0,
      top_k=0,
      max_new_tokens=1024
    ):

  messages = get_message_format(prompts)

  input_ids = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        padding=True,
        return_tensors="pt",
      )
  input_ids = input_ids.to(model.device)
  prompt_padded_len = len(input_ids[0])

  gen_tokens = model.generate(
        input_ids,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        max_new_tokens=max_new_tokens,
        do_sample=True,
      )

  # get only generated tokens
  gen_tokens = [
      gt[prompt_padded_len:] for gt in gen_tokens
    ]

  gen_text = tokenizer.batch_decode(gen_tokens, skip_special_tokens=True)
  return gen_text

"""Let's do a quick test of the model generations in English, Vietnamese, Japanese, and Turkish, which are all part of the original set of 23 optimized languages."""

# Test generations on langauges in Aya 23 set
# prompts = [
#     "Write a list of three fruits and tell me about each of them", # English
#     "Viết danh sách ba loại trái cây và kể cho tôi nghe về từng loại trái cây đó", # Vietnamese
#     "3 つの果物のリストを書いて、それぞれについて教えてください", # Japanese
#     "Üç meyveden oluşan bir liste yazın ve bana her birini anlatın" # Turkish
# ]

# generations = generate_aya(model, prompts)

# for p, g in zip(prompts, generations):
#   print(
#       "PROMPT", p ,"RESPONSE", g, "\n", sep="\n"
#     )

"""As expected, the model performs well in the languages that were part of the original set of 23 optimized languages Let's do a quick test of the model generations in Bengali, which is not part of the original set of 23 optimized languages.

"""

prompts = [
  'Translate from Javanese to Indonesian: "Roti-roti sing disajekne nggarai aku nostalgianan. Kabeh model roti jaman biyen, saka tampilane utawa rasa. Rotine enak lan regane uga mirah."'
]

generations = generate_aya(model, prompts)

for p, g in zip(prompts, generations):
  print(
      "PROMPT", p ,"RESPONSE", g, "\n", sep="\n"
    )

"""While the model is able to generate a response in the correct target language of Bengali, the translation could be improved. The response translated back into English is "Selling their simple, barrier-free solutions is the most advanced on the market".

## Dataset Setup

Here we load an English to Bengali translation dataset from the Aya Collection. We filter the dataset to only include Bengali examples and define a formatting function to format the prompts to follow the chat template used by Aya Expanse models. This formatting function will be passed to the `SFTTrainer` below for training.
"""

# Load and prepare training dataset
from datasets import Dataset
import pandas as pd
file_path = './translation_data_simple_seq2seq.jsonl'
df = pd.read_json(path_or_buf=file_path, lines=True)
dataset = Dataset.from_pandas(df)

# Check for empty targets
empty_targets = [ex for ex in dataset if not ex['target'] or ex['target'].strip() == ""]
print(f"Number of examples with empty targets: {len(empty_targets)}")
dataset = dataset.filter(lambda x: x['target'] and x['target'].strip() != "")

# Load and prepare validation dataset
file_path = './translation_data_simple_seq2seq_validation.jsonl'
val_df = pd.read_json(path_or_buf=file_path, lines=True)
val_dataset = Dataset.from_pandas(val_df)

# Load an English to Bengali translation dataset from Aya Collection
# dataset = load_dataset("CohereForAI/aya_collection", "templated_indic_sentiment")['train']
# dataset = dataset.filter(lambda example: example['language']=='ben')

def formatting_prompts_func(example):
    output_texts = []
    for i in range(len(example['text'])):
        text = f"<|START_OF_TURN_TOKEN|><|USER_TOKEN|>Translate from Javanese to Indonesian: {example['text'][i]}<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>{example['target'][i]}"
        output_texts.append(text)
    return output_texts

"""Here is an example prompt and response from the dataset:"""

print(f"PROMPT\n{dataset['text'][0]}")
print(f"RESPONSE\n{dataset['target'][0]}")

"""## SFT Model Training
Below we configure SFT training Aya Expanse on the NusaX dataset constructed above. We use LoRA for efficient fine-tuning and thus only update and save the LoRA adapters during training.
"""

# Training Configuration
training_arguments = TrainingArguments(
    output_dir="results",
    num_train_epochs=20,
    per_device_train_batch_size=TRAIN_BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACC_STEPS,
    gradient_checkpointing=USE_GRAD_CHECKPOINTING,
    optim="paged_adamw_32bit",
    save_steps=50,
    logging_steps=10,
    learning_rate=1e-3,
    weight_decay=0.001,
    fp16=False,
    bf16=True,
    warmup_ratio=0.05,
    group_by_length=True,
    lr_scheduler_type="constant",
    report_to="none"
)

peft_config = LoraConfig(
    lora_alpha=32,
    r=32,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"]
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    # max_seq_length=TRAIN_MAX_SEQ_LENGTH,
    tokenizer=tokenizer,
    args=training_arguments,
    formatting_func=formatting_prompts_func
)

# Train the model
trainer.train()

# Save the model to disk
trainer.model.save_pretrained(save_directory='./outputs/aya-expanse-javanese-sft')
model.config.use_cache = True
model.eval()

"""## Testing the Fine-Tuned Model
Now, let's load the fine-tuned model and test it on the same Bengali prompt as before.
"""

# Test Bengali inference on loaded fine-tuned model

# Load Model and LoRA Adapter
quantization_config = None
if QUANTIZE_4BIT:
  quantization_config = BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_use_double_quant=True,
      bnb_4bit_compute_dtype=torch.bfloat16,
  )

attn_implementation = None
if USE_FLASH_ATTENTION:
  attn_implementation="flash_attention_2"

loaded_sft_model = AutoModelForCausalLM.from_pretrained(
          MODEL_PATH,
          quantization_config=quantization_config,
          attn_implementation=attn_implementation,
          torch_dtype=torch.bfloat16,
        )
loaded_sft_model = loaded_sft_model.to(device)
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
loaded_sft_model.load_adapter("./outputs/aya-expanse-javanese-sft")


prompts = [
  'Translate from Javanese to Indonesian: "Roti-roti sing disajekne nggarai aku nostalgianan. Kabeh model roti jaman biyen, saka tampilane utawa rasa. Rotine enak lan regane uga mirah."'
]

generations = generate_aya(loaded_sft_model, prompts)

for p, g in zip(prompts, generations):
  print(
      "PROMPT", p ,"RESPONSE", g, "\n", sep="\n"
    )

"""The model output translated back into English is "The rates are competitive, almost always the best", which is much better than the original model ouput before fine-tuning as expected."""